### ISSUE TITLE
Notification Api

### ISSUE THREAD

**Issue by tim-hellhake** [tim-hellhake/google-home-adapter#2]
Mentioned in https://github.com/tim-hellhake/google-home-adapter/issues/1

**Comment by tim-hellhake** [comment]
As mentioned in https://github.com/tim-hellhake/google-home-adapter/issues/1

**Comment by tim-hellhake** [comment]
I added an implementation of the notifier api.
Could you please test it @Beejeedeb?
I prepared a [release](https://github.com/tim-hellhake/google-home-adapter/releases/tag/0.4.0).

**Comment by tim-hellhake** [comment]
The priority of the notification is currently ignored.
I'm not sure how to implement it.
I could define a volume level for each priority.
What do you think?

**Comment by Beejeedeb** [comment]
Hi Tim,

I get the following Errors after installing release 0.4.0. Looks like There is a module missing.

2019-08-03 20:24:20.047 INFO   : Loading add-on: google-home-adapter
2019-08-03 20:24:20.850 INFO   : google-home: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-08-03 20:24:20.898 INFO   : google-home: Loading add-on for google-home-adapter from /home/pi/.mozilla-iot/addons/google-home-adapter
2019-08-03 20:24:21.605 ERROR  : google-home: { Error: Cannot find module './google-home-device'
2019-08-03 20:24:21.607 ERROR  : google-home:     at Function.Module._resolveFilename (module.js:548:15)
2019-08-03 20:24:21.609 ERROR  : google-home:     at Function.Module._load (module.js:475:25)
2019-08-03 20:24:21.610 ERROR  : google-home:     at Module.require (module.js:597:17)
2019-08-03 20:24:21.612 ERROR  : google-home:     at require (internal/module.js:11:18)
2019-08-03 20:24:21.613 ERROR  : google-home:     at Object.<anonymous> (/home/pi/.mozilla-iot/addons/google-home-adapter/lib/google-home-adapter.js:10:30)
2019-08-03 20:24:21.614 ERROR  : google-home:     at Module._compile (module.js:653:30)
2019-08-03 20:24:21.616 ERROR  : google-home:     at Object.Module._extensions..js (module.js:664:10)
2019-08-03 20:24:21.617 ERROR  : google-home:     at Module.load (module.js:566:32)
2019-08-03 20:24:21.618 ERROR  : google-home:     at tryModuleLoad (module.js:506:12)
2019-08-03 20:24:21.619 ERROR  : google-home:     at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' }

**Comment by tim-hellhake** [comment]
I think I found the issue.
A new [release](https://github.com/tim-hellhake/google-home-adapter/releases/tag/0.4.1) is available.

**Comment by Beejeedeb** [comment]
It works but it is still very limited. I don't know what level does and I still miss a field for the language setting and a field for sound level. A field where you enter a value is imo just as practical as a slider. Will the sound level also be set back to the original value when the alarm is over?

A notification is imo different from an alarm, I see a notification being used more often for a less urgent message via a communication medium such as Twitter or e-mail. An alarm is more urgent and an action must be taken immediately in case of TTS that the sound level goes up and the text is repeated until the alarm is over or the house is burned down :-) For example, with another add-on, for an alarm the lamps must start flashing in alternating red and blue.

We are now trying to put an alarm in a notification property while it is not. Just my five cents :-)

**Comment by tim-hellhake** [comment]
> I don't know what level does

At the moment it does nothing.
I thought about using different volume levels.

The notification API only knows `title`, `message` and `level`.
As no language can be specified the default language is used.
It can be changed in the config.
I also added a default volume option to compensate for the missing volume parameter.

> Will the sound level also be set back to the original value when the alarm is over?

It should use the default volume to playback the message and return back to the original volume at the end.

> We are now trying to put an alarm in a notification property while it is not.

Indeed.

**Comment by Beejeedeb** [comment]
notification is just fine for notifications, but the notification api is very limited and a bit confusing if used for the Google TTS. This because the TTS add on can far more cool things.

**Comment by tim-hellhake** [comment]
I think there is nothing left to be done here.
If you miss anything, feel free to open a new issue.
